/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aplicacion.Accion;
import aplicacion.Empresa;
import aplicacion.HacerOfertaVenta;
import aplicacion.Usuario;
import java.awt.Color;
import java.util.Date;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author alex
 */
public class VHistorialOfertaVenta extends javax.swing.JDialog {

    aplicacion.FachadaAplicacion fa;
    private VPrincipal vp;
    private Usuario usuario;

    public VHistorialOfertaVenta(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, Usuario usuario) {
        super(parent, modal);
        this.fa = fa;
        this.usuario = usuario;
        initComponents();
        this.getContentPane().setBackground(Color.white);
        BuscarTabla("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textoFiltrado = new javax.swing.JTextField();
        PrecioMaxim = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaOfertaVenta = new javax.swing.JTable();
        btnBuscar = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JLabel();
        btnModificar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("HISTORIAL OFERTA VENTA");

        textoFiltrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoFiltradoActionPerformed(evt);
            }
        });

        PrecioMaxim.setText("Empresa");

        TablaOfertaVenta.setModel(new ModeloTablaOfertaVenta());
        TablaOfertaVenta.setColumnSelectionAllowed(true);
        TablaOfertaVenta.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaOfertaVenta);
        TablaOfertaVenta.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VPrincipal/botonBuscar.png"))); // NOI18N
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VRegistro/botonVolver.png"))); // NOI18N
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnGenerales/botonEliminar.png"))); // NOI18N
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnGenerales/botonModificar.png"))); // NOI18N
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PrecioMaxim)
                                        .addGap(18, 18, 18)
                                        .addComponent(textoFiltrado, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addGap(176, 176, 176)))
                                .addComponent(btnBuscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(btnModificar)
                        .addGap(26, 26, 26)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoFiltrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PrecioMaxim))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBuscar)
                        .addGap(10, 10, 10)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoFiltradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoFiltradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoFiltradoActionPerformed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        BuscarTabla(this.textoFiltrado.getText());    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        int filaSeleccionada = TablaOfertaVenta.getSelectedRow();
        if (filaSeleccionada != -1) {
            HacerOfertaVenta oferta;

            Empresa e = fa.consultarEmpresas(TablaOfertaVenta.getValueAt(filaSeleccionada, 6).toString()).get(0);

            oferta = new HacerOfertaVenta((Date) TablaOfertaVenta.getValueAt(filaSeleccionada, 1),
                    null,
                    true,
                    e,
                    usuario,
                    null);
            fa.borrarOferta(oferta);
        } else {
            fa.muestraExcepcion("SELECCIONA UNA FILA DE LA TABLA");
        }


        BuscarTabla(this.textoFiltrado.getText());    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        try {
            int filaSeleccionada = TablaOfertaVenta.getSelectedRow();
            if (filaSeleccionada != -1) {
                HacerOfertaVenta oferta;

                Empresa e = fa.consultarEmpresas(TablaOfertaVenta.getValueAt(filaSeleccionada, 6).toString()).get(0);

                oferta = new HacerOfertaVenta((Date) TablaOfertaVenta.getValueAt(filaSeleccionada, 1),
                        null,
                        true,
                        e,
                        usuario,
                        null);

                fa.modificarOferta(oferta, Integer.parseInt(TablaOfertaVenta.getValueAt(filaSeleccionada, 2).toString()));
                
            } else {
                fa.muestraExcepcion("SELECCIONA UNA FILA DE LA TABLA");
            }
        } catch (NumberFormatException e) {
            fa.muestraExcepcion("Inserte un número");
        }
        BuscarTabla(this.textoFiltrado.getText());    }//GEN-LAST:event_btnModificarMouseClicked


    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    //Vaciar tabla
    private void vaciarTabla() {
        int rowCount = TablaOfertaVenta.getModel().getRowCount();
        DefaultTableModel modelo = (DefaultTableModel) TablaOfertaVenta.getModel();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
        TablaOfertaVenta.setModel(modelo);
    }

    //Actualiza el contenido de la tabla
    private void BuscarTabla(String empresa) {
        DefaultTableModel modelo = new DefaultTableModel();
        Iterator<HacerOfertaVenta> ofertasAccionesIterator = fa.filtrarOfertasUsuario(usuario, empresa).iterator();
        HacerOfertaVenta auxiliar;

        modelo.addColumn("Precio");
        modelo.addColumn("FechaOferta");
        modelo.addColumn("Numero de participaciones");
        modelo.addColumn("Disponibilidad");
        modelo.addColumn("Nombre Comercial");
        modelo.addColumn("CIF");
        modelo.addColumn("IDEmpresa");

        while (ofertasAccionesIterator.hasNext()) {
            auxiliar = ofertasAccionesIterator.next();

            modelo.addRow(new Object[]{
                auxiliar.getPrecio(),
                auxiliar.getFechaOferta(),
                auxiliar.getNumeroParticipaciones(),
                auxiliar.isDisponibilidad(),
                auxiliar.getEmpresa().getNombreComercial(),
                auxiliar.getEmpresa().getCIF(),
                auxiliar.getEmpresa().getUsuario().getId_usuario()});
        }

        TablaOfertaVenta.setModel((TableModel) modelo);
        if (modelo.getRowCount() > 0) {
            TablaOfertaVenta.setRowSelectionInterval(0, 0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PrecioMaxim;
    private javax.swing.JTable TablaOfertaVenta;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnModificar;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textoFiltrado;
    // End of variables declaration//GEN-END:variables
}
