
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aplicacion.Accion;
import aplicacion.Anuncios;
import aplicacion.Empresa;
import aplicacion.Usuario;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author alex
 */
public class VMiEmpresa extends javax.swing.JDialog {

    aplicacion.FachadaAplicacion fa;
    private Empresa empresa;
    private VPrincipal vp;
    private String idAntiguo;

    /**
     * Creates new form VMiEmpresa
     */
    public VMiEmpresa(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, Empresa empresa, int opcion) {
        super(parent, modal);
        this.fa = fa;
        this.empresa = empresa;
        initComponents();
        this.getContentPane().setBackground(Color.white);

        this.TextoCIF.setText(empresa.getCIF());
        this.TextoCalle.setText(empresa.getCalle());
        this.TextoID.setText(empresa.getUsuario().getId_usuario());
        this.TextoNombre.setText(empresa.getNombreComercial());
        this.TextoNumero.setText(empresa.getNumero().toString());
        this.TextoParticipaciones.setText(empresa.getParticipaciones().toString());
        this.TextoParticipacionesSinVende.setText(empresa.getParticipacionesSinVender().toString());
        this.TextoPoblacion.setText(empresa.getCiudad());
        this.TextoTelefono.setText(empresa.getTelefono().toString());
        
        this.idAntiguo = this.TextoID.getText();
        
        TextoParticipaciones.setEditable(false);
        TextoParticipacionesSinVende.setEditable(false);

        if(opcion == 0) {
           this.jTabbedPane1.setSelectedIndex(1);
        }
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        MiPerfil = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TextoNombre = new javax.swing.JTextField();
        TextoID = new javax.swing.JTextField();
        TextoCIF = new javax.swing.JTextField();
        TextoTelefono = new javax.swing.JTextField();
        TextoPoblacion = new javax.swing.JTextField();
        TextoParticipacionesSinVende = new javax.swing.JTextField();
        TextoCalle = new javax.swing.JTextField();
        TextoParticipaciones = new javax.swing.JTextField();
        TextoNumero = new javax.swing.JTextField();
        etiquetaResultadoAccion = new javax.swing.JLabel();
        btnVolverPerfil = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JLabel();
        btnDarseBaja = new javax.swing.JLabel();
        btnCambiarContrasena = new javax.swing.JButton();
        MisAnuncios = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        textoFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAnuncios = new javax.swing.JTable();
        btnBuscar = new javax.swing.JLabel();
        btnVolverAnuncios = new javax.swing.JLabel();
        btnCrearAnuncio = new javax.swing.JLabel();
        btnRealizarPago = new javax.swing.JButton();
        btnBorrarAnuncio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        MiPerfil.setBackground(new java.awt.Color(255, 255, 255));
        MiPerfil.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MI PERFIL");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("CIF:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("NOMBRE COMERCIAL:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("POBLACIÓN:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("CALLE:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("PORTAL:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("TELÉFONO:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("PARTICIPACIONES ADQUIRIDAS:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("PARTICIPACIONES SIN VENDER:");

        TextoCIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoCIFActionPerformed(evt);
            }
        });

        TextoParticipaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoParticipacionesActionPerformed(evt);
            }
        });

        etiquetaResultadoAccion.setForeground(new java.awt.Color(255, 0, 0));
        etiquetaResultadoAccion.setText("textoEjemplo34");

        btnVolverPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VRegistro/botonVolver.png"))); // NOI18N
        btnVolverPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverPerfilMouseClicked(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnGenerales/BotonGuardar.png"))); // NOI18N
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        btnDarseBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnGenerales/botonDarBaja.png"))); // NOI18N
        btnDarseBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDarseBajaMouseClicked(evt);
            }
        });
        btnDarseBaja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnDarseBajaKeyTyped(evt);
            }
        });

        btnCambiarContrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnGenerales/botonCambiarContraseña.png"))); // NOI18N
        btnCambiarContrasena.setBorderPainted(false);
        btnCambiarContrasena.setContentAreaFilled(false);
        btnCambiarContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCambiarContrasenaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MiPerfilLayout = new javax.swing.GroupLayout(MiPerfil);
        MiPerfil.setLayout(MiPerfilLayout);
        MiPerfilLayout.setHorizontalGroup(
            MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiPerfilLayout.createSequentialGroup()
                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MiPerfilLayout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jLabel1))
                    .addGroup(MiPerfilLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(MiPerfilLayout.createSequentialGroup()
                                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MiPerfilLayout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TextoPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(MiPerfilLayout.createSequentialGroup()
                                                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(MiPerfilLayout.createSequentialGroup()
                                                        .addComponent(TextoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(113, 113, 113))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MiPerfilLayout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addGap(51, 51, 51)))
                                                .addComponent(TextoCIF, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MiPerfilLayout.createSequentialGroup()
                                                .addComponent(TextoCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TextoParticipacionesSinVende, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(TextoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MiPerfilLayout.createSequentialGroup()
                                                .addComponent(btnVolverPerfil)
                                                .addGap(1, 1, 1))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MiPerfilLayout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextoID, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(MiPerfilLayout.createSequentialGroup()
                                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(MiPerfilLayout.createSequentialGroup()
                                        .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(MiPerfilLayout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(59, 59, 59)
                                                .addComponent(TextoParticipaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 45, Short.MAX_VALUE))
                                            .addGroup(MiPerfilLayout.createSequentialGroup()
                                                .addComponent(btnGuardar)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnCambiarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(btnDarseBaja))))
                                .addGap(148, 148, 148))
                            .addComponent(etiquetaResultadoAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        MiPerfilLayout.setVerticalGroup(
            MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(TextoCIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(33, 33, 33)
                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TextoPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TextoCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(TextoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TextoParticipaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(TextoParticipacionesSinVende, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(etiquetaResultadoAccion)
                .addGap(26, 26, 26)
                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnVolverPerfil)
                        .addComponent(btnDarseBaja)
                        .addComponent(btnGuardar))
                    .addComponent(btnCambiarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        etiquetaResultadoAccion.setVisible(false);

        jTabbedPane1.addTab("Datos Perfil", MiPerfil);

        MisAnuncios.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Filtro:");

        textoFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoFiltroActionPerformed(evt);
            }
        });

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Anuncio");
        modelo.addColumn("Descripción");
        modelo.addColumn("Fecha Publicación");
        modelo.addColumn("Fecha Pago");
        tablaAnuncios.setModel((TableModel) modelo);
        jScrollPane1.setViewportView(tablaAnuncios);
        if (tablaAnuncios.getColumnModel().getColumnCount() > 0) {
            tablaAnuncios.getColumnModel().getColumn(0).setResizable(false);
            tablaAnuncios.getColumnModel().getColumn(1).setResizable(false);
            tablaAnuncios.getColumnModel().getColumn(2).setResizable(false);
            tablaAnuncios.getColumnModel().getColumn(3).setResizable(false);
        }
        actualizarTabla("");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VPrincipal/botonBuscar.png"))); // NOI18N
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        btnVolverAnuncios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VRegistro/botonVolver.png"))); // NOI18N
        btnVolverAnuncios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverAnunciosMouseClicked(evt);
            }
        });

        btnCrearAnuncio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VPrincipal/BotonCrearAnuncio.png"))); // NOI18N
        btnCrearAnuncio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearAnuncioMouseClicked(evt);
            }
        });

        btnRealizarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnGenerales/botonRealizaraPago.png"))); // NOI18N
        btnRealizarPago.setBorderPainted(false);
        btnRealizarPago.setContentAreaFilled(false);
        btnRealizarPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRealizarPagoMouseClicked(evt);
            }
        });

        btnBorrarAnuncio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnGenerales/botonBorrarAnuncio.png"))); // NOI18N
        btnBorrarAnuncio.setBorderPainted(false);
        btnBorrarAnuncio.setContentAreaFilled(false);
        btnBorrarAnuncio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarAnuncioMouseClicked(evt);
            }
        });
        btnBorrarAnuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarAnuncioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MisAnunciosLayout = new javax.swing.GroupLayout(MisAnuncios);
        MisAnuncios.setLayout(MisAnunciosLayout);
        MisAnunciosLayout.setHorizontalGroup(
            MisAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MisAnunciosLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(MisAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MisAnunciosLayout.createSequentialGroup()
                        .addComponent(btnBorrarAnuncio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRealizarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCrearAnuncio)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolverAnuncios))
                    .addGroup(MisAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(MisAnunciosLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(18, 18, 18)
                            .addComponent(textoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(47, 47, 47)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        MisAnunciosLayout.setVerticalGroup(
            MisAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MisAnunciosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(MisAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscar)
                    .addGroup(MisAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(MisAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MisAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(MisAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCrearAnuncio)
                            .addComponent(btnVolverAnuncios))
                        .addComponent(btnRealizarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBorrarAnuncio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mis Anuncios", MisAnuncios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoFiltroActionPerformed

    private void btnVolverAnunciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverAnunciosMouseClicked
        this.dispose();
        fa.visualizarVentanaPrincipal(empresa.getUsuario());
    }//GEN-LAST:event_btnVolverAnunciosMouseClicked

    private void btnCrearAnuncioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearAnuncioMouseClicked
        fa.visualizarCrearAnuncio(empresa);
        actualizarTabla("");
    }//GEN-LAST:event_btnCrearAnuncioMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        actualizarTabla(textoFiltro.getText());
// TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnRealizarPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRealizarPagoMouseClicked
        
        int filaSeleccionada = tablaAnuncios.getSelectedRow();
        if(filaSeleccionada != -1){
        fa.visualizarPagoParticipaciones(empresa, 1, Integer.parseInt(tablaAnuncios.getValueAt(filaSeleccionada, 0).toString()));        
        actualizarTabla("");
        }
    }//GEN-LAST:event_btnRealizarPagoMouseClicked
    
    private void btnDarseBajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDarseBajaMouseClicked

        Usuario user = empresa.getUsuario();
        if(!fa.usuarioPoseeAcciones(user)){
            user.setEnEspera(-1);
            fa.modificarUsuario(user, user.getId_usuario());
            this.dispose();
            fa.muestraExcepcion("Ha solicitado darse de baja correctamente.");            
            fa.iniciaInterfazUsuario();

        }else{
            fa.muestraExcepcion("No se ha podido dar de baja. Compruebe sus participaciones activas.");
        }

    }//GEN-LAST:event_btnDarseBajaMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        this.guardarDatos();
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnVolverPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverPerfilMouseClicked
        this.dispose();
        fa.visualizarVentanaPrincipal(empresa.getUsuario());
    }//GEN-LAST:event_btnVolverPerfilMouseClicked

    private void TextoParticipacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoParticipacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoParticipacionesActionPerformed

    private void TextoCIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoCIFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoCIFActionPerformed

    private void btnCambiarContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiarContrasenaMouseClicked

        Usuario usuario = fa.consultarUnUsuario(TextoID.getText());
        fa.visualizarCambiarContrasena(usuario);

        //fa.visualizarCambiarContrasena(empresa);

    }//GEN-LAST:event_btnCambiarContrasenaMouseClicked

    private void btnBorrarAnuncioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarAnuncioMouseClicked
        int filaSeleccionada = tablaAnuncios.getSelectedRow();
        if (filaSeleccionada != -1){
        fa.borrarAnuncio(Integer.parseInt(tablaAnuncios.getValueAt(filaSeleccionada, 0).toString())); 
        actualizarTabla("");
        }
    }//GEN-LAST:event_btnBorrarAnuncioMouseClicked

    private void btnDarseBajaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDarseBajaKeyTyped
                                           
        // TODO add your handling code here:
        Usuario user = empresa.getUsuario();
        if(!fa.usuarioPoseeAcciones(user)){
            user.setEnEspera(-1);
            fa.modificarUsuario(user, user.getId_usuario());
            this.dispose();
            fa.muestraExcepcion("Ha solicitado darse de baja correctamente.");            
            fa.iniciaInterfazUsuario();

        }else{
            fa.muestraExcepcion("No se ha podido dar de baja. Compruebe sus participaciones activas.");
        }
    }//GEN-LAST:event_btnDarseBajaKeyTyped

    private void btnBorrarAnuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarAnuncioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarAnuncioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MiPerfil;
    private javax.swing.JPanel MisAnuncios;
    private javax.swing.JTextField TextoCIF;
    private javax.swing.JTextField TextoCalle;
    private javax.swing.JTextField TextoID;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JTextField TextoNumero;
    private javax.swing.JTextField TextoParticipaciones;
    private javax.swing.JTextField TextoParticipacionesSinVende;
    private javax.swing.JTextField TextoPoblacion;
    private javax.swing.JTextField TextoTelefono;
    private javax.swing.JButton btnBorrarAnuncio;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JButton btnCambiarContrasena;
    private javax.swing.JLabel btnCrearAnuncio;
    private javax.swing.JLabel btnDarseBaja;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JButton btnRealizarPago;
    private javax.swing.JLabel btnVolverAnuncios;
    private javax.swing.JLabel btnVolverPerfil;
    private javax.swing.JLabel etiquetaResultadoAccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaAnuncios;
    private javax.swing.JTextField textoFiltro;
    // End of variables declaration//GEN-END:variables

    public void guardarDatos() {
        if (!TextoCIF.getText().isEmpty() && !TextoCalle.getText().isEmpty() && !TextoID.getText().isEmpty() && !TextoNombre.getText().isEmpty() && !TextoNumero.getText().isEmpty() && !TextoParticipaciones.getText().isEmpty() && !TextoParticipacionesSinVende.getText().isEmpty() && !TextoPoblacion.getText().isEmpty() && !TextoTelefono.getText().isEmpty()) {

            try {
                
                Integer.parseInt(TextoParticipacionesSinVende.getText());
                int telefono = Integer.parseInt(TextoTelefono.getText());
                Integer.parseInt(TextoParticipaciones.getText());
                int numero = Integer.parseInt(TextoNumero.getText());
                
                if(numero>0 && telefono>0){

                    Usuario user = fa.consultarUnUsuario(idAntiguo);
                    user.setId_usuario(TextoID.getText());
                    fa.modificarUsuario(user, idAntiguo);
                    fa.guardarDatosEmpresa(TextoCIF.getText(), TextoCalle.getText(), TextoID.getText(), TextoNombre.getText(), Integer.parseInt(TextoNumero.getText()), Integer.parseInt(TextoParticipaciones.getText()), Integer.parseInt(TextoParticipacionesSinVende.getText()), TextoPoblacion.getText(), Integer.parseInt(TextoTelefono.getText()));

                    empresa.setCalle(this.TextoCalle.getText());
                    empresa.setNumero(Integer.parseInt(this.TextoNumero.getText()));
                    empresa.setParticipaciones(Integer.parseInt(this.TextoParticipaciones.getText()));
                    empresa.setParticipacionesSinVender(Integer.parseInt(this.TextoParticipacionesSinVende.getText()));
                    empresa.setCiudad(this.TextoPoblacion.getText());
                    empresa.setTelefono(Integer.parseInt(this.TextoTelefono.getText()));
                    empresa.setNombreComercial(this.TextoNombre.getText());

                    fa.muestraExcepcion("Empresa modificada correctamente.");
                    empresa = fa.consultarUnaEmpresa(user);
                }else{
                    fa.muestraExcepcion("Introduzca números positivos.");    
                }
            } catch (NumberFormatException e) {
                etiquetaResultadoAccion.setText("Alguno de los campos teléfono y número tienes letras.");
                etiquetaResultadoAccion.setVisible(true);
            }
        } else {
            etiquetaResultadoAccion.setText("Completa todos los campos.");
            etiquetaResultadoAccion.setVisible(true);
        }

    }

    //Funcion para actualizar la tabla de los anuncios (SIN ACABAR)
    private void actualizarTabla(String cadenaContenida) {
        DefaultTableModel modelo = new DefaultTableModel();
        Iterator<Anuncios> anunciosIterator = fa.obtenerAnuncios(empresa.getCIF(), textoFiltro.getText()).iterator();
        Anuncios auxiliar;
        modelo.addColumn("ID Anuncio");
        modelo.addColumn("Descripción");
        modelo.addColumn("Fecha Publicación");
        modelo.addColumn("Fecha Pago");
        while (anunciosIterator.hasNext()) {
            auxiliar = anunciosIterator.next();
            modelo.addRow(new Object[]{auxiliar.getId_anuncio(), auxiliar.getInformacion(),
                auxiliar.getFechaPublicacion(), auxiliar.getFechaPago()});
        }
        tablaAnuncios.setModel((TableModel) modelo);
        if (modelo.getRowCount() > 0) {
            tablaAnuncios.setRowSelectionInterval(0, 0);
        }
    }
}
