/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aplicacion.Empresa;
import aplicacion.FachadaAplicacion;
import java.awt.Color;

/**
 *
 * @author usuario
 */
public class VPagosDividendos extends javax.swing.JDialog {
    FachadaAplicacion fa;
    Empresa empresa;

    /**
     * Creates new form VPagosDividendos
     */
    public VPagosDividendos(java.awt.Frame parent, boolean modal, FachadaAplicacion fa, Empresa empresa) {
        super(parent, modal);
        this.empresa = empresa;
        this.fa = fa;
        initComponents();
        this.getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAnunciado = new javax.swing.JButton();
        btnSinAnunciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnAnunciado.setBackground(new java.awt.Color(255, 255, 255));
        btnAnunciado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnGenerales/botonPagoAnunciado.png"))); // NOI18N
        btnAnunciado.setBorder(null);
        btnAnunciado.setBorderPainted(false);
        btnAnunciado.setContentAreaFilled(false);
        btnAnunciado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnunciadoMouseClicked(evt);
            }
        });

        btnSinAnunciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnGenerales/botonPagoSinAnunciar.png"))); // NOI18N
        btnSinAnunciar.setBorderPainted(false);
        btnSinAnunciar.setContentAreaFilled(false);
        btnSinAnunciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSinAnunciarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnAnunciado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnSinAnunciar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(btnAnunciado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSinAnunciar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnunciadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnunciadoMouseClicked
        // TODO add your handling code here:
        fa.visualizarPerfilEmpresa(empresa, 0);
    }//GEN-LAST:event_btnAnunciadoMouseClicked

    private void btnSinAnunciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSinAnunciarMouseClicked
        // TODO add your handling code here:
        fa.visualizarPagoParticipaciones(empresa, 0, 0);
    }//GEN-LAST:event_btnSinAnunciarMouseClicked

    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnunciado;
    private javax.swing.JButton btnSinAnunciar;
    // End of variables declaration//GEN-END:variables
}
