/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aplicacion.Inversor;
import aplicacion.Usuario;
import java.awt.Color;

/**
 *
 * @author itocd
 */
public class VPerfil extends javax.swing.JDialog {

    aplicacion.FachadaAplicacion fa;
    private Inversor inversor;
    VAviso va;
    private String idAntiguo;

    /**
     * Creates new form VPerfi
     */
    public VPerfil(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, Inversor inversor) {
        super(parent, modal);
        this.fa = fa;
        this.inversor = inversor;
        
        this.getContentPane().setBackground(Color.white);

        idAntiguo = inversor.getId_usuario().getId_usuario();
        
        initComponents();
        
        
        this.TextoID.setText(inversor.getId_usuario().getId_usuario());
        this.TextoNombre.setText(inversor.getNombre());
        this.TextoAp1.setText(inversor.getApellido1());
        this.TextoAp2.setText(inversor.getApellido2());
        this.TextoDNI.setText(inversor.getDNI());
        this.TextoCalle.setText(inversor.getCalle());
        this.TextoPortal.setText(inversor.getPortal().toString());
        this.TextoPiso.setText(inversor.getPiso().toString());
        this.TextoPuerta.setText(inversor.getPuerta());
        this.TextoTelefono.setText(inversor.getTelefono().toString());

        
        
        this.etiquetaResultadoAccion.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextoID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextoNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextoAp1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TextoAp2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TextoDNI = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TextoCalle = new javax.swing.JTextField();
        TextoPortal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TextoPiso = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TextoPuerta = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TextoTelefono = new javax.swing.JTextField();
        etiquetaResultadoAccion = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JLabel();
        btnDarBaja = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnCambiarPwd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MI PERFIL");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("NOMBRE");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("APELLIDO 1");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("APELLIDO 2");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("DNI");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("CALLE");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("PORTAL");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("PISO");

        TextoPiso.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("PUERTA");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("TELÉFONO");

        etiquetaResultadoAccion.setForeground(new java.awt.Color(255, 0, 0));
        etiquetaResultadoAccion.setText("*textoError");

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnGenerales/BotonGuardar.png"))); // NOI18N
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        btnDarBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnGenerales/botonDarBaja.png"))); // NOI18N
        btnDarBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDarBajaMouseClicked(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VRegistro/botonVolver.png"))); // NOI18N
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        btnCambiarPwd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnGenerales/botonCambiarContraseña.png"))); // NOI18N
        btnCambiarPwd.setBorderPainted(false);
        btnCambiarPwd.setContentAreaFilled(false);
        btnCambiarPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarPwdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(TextoID, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(TextoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel8)
                        .addGap(71, 71, 71)
                        .addComponent(TextoPortal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(TextoPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TextoPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel11)
                        .addGap(71, 71, 71)
                        .addComponent(TextoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(TextoCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(btnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(btnCambiarPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btnDarBaja)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(TextoAp1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel5)
                                .addGap(50, 50, 50)
                                .addComponent(TextoAp2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(etiquetaResultadoAccion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextoAp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoAp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7))
                            .addComponent(TextoCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextoPortal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11))
                    .addComponent(TextoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(etiquetaResultadoAccion)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnDarBaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCambiarPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(btnGuardar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
        //Modificar
        this.guardarDatosUsuario();
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnDarBajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDarBajaMouseClicked
                                      
        // TODO add your handling code here:
        Usuario user = inversor.getId_usuario();
        if(!fa.usuarioPoseeAcciones(user)){
            user.setEnEspera(-1);
            fa.modificarUsuario(user, user.getId_usuario());
            this.dispose();
            fa.muestraExcepcion("Ha solicitado darse de baja correctamente.");            
            fa.iniciaInterfazUsuario();

        }else{
            fa.muestraExcepcion("No se ha podido dar de baja. Compruebe sus participaciones activas.");
        }
    }//GEN-LAST:event_btnDarBajaMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
        fa.visualizarVentanaPrincipal(inversor.getId_usuario());
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnCambiarPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarPwdActionPerformed
        // TODO add your handling code here:
        Usuario usuario = fa.consultarUnUsuario(inversor.getId_usuario().getId_usuario());
        fa.visualizarCambiarContrasena(usuario);
    }//GEN-LAST:event_btnCambiarPwdActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextoAp1;
    private javax.swing.JTextField TextoAp2;
    private javax.swing.JTextField TextoCalle;
    private javax.swing.JTextField TextoDNI;
    private javax.swing.JTextField TextoID;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JTextField TextoPiso;
    private javax.swing.JTextField TextoPortal;
    private javax.swing.JTextField TextoPuerta;
    private javax.swing.JTextField TextoTelefono;
    private javax.swing.JButton btnCambiarPwd;
    private javax.swing.JLabel btnDarBaja;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel etiquetaResultadoAccion;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    public void guardarDatosUsuario() {
        if (!TextoNombre.getText().isEmpty() && !TextoAp1.getText().isEmpty() && !TextoAp2.getText().isEmpty() && !TextoID.getText().isEmpty()
                && !TextoCalle.getText().isEmpty() && !TextoPortal.getText().isEmpty() && !TextoPiso.getText().isEmpty() && !TextoPuerta.getText().isEmpty() && !TextoTelefono.getText().isEmpty()) {
            try {
                //Comprobación errores a int
                int Telefono;
                Telefono = Integer.parseInt(this.TextoTelefono.getText());
                int portal = Integer.parseInt(TextoPortal.getText());
                int piso = Integer.parseInt(TextoPiso.getText());
                
                if (piso>0 && portal > 0 && Telefono > 0){
                    Inversor newInversor = new Inversor(fa.consultarUnUsuario(idAntiguo), TextoDNI.getText(), TextoNombre.getText(), TextoAp1.getText(),
                            TextoAp2.getText(), TextoCalle.getText(), Integer.parseInt(TextoPortal.getText()), Integer.parseInt(TextoPiso.getText()),
                            TextoPuerta.getText(), Integer.parseInt(TextoTelefono.getText()));

                    newInversor.setApellido1(TextoAp1.getText());
                    newInversor.setApellido2(TextoAp2.getText());
                    newInversor.setCalle(TextoCalle.getText());
                    newInversor.setDNI(TextoDNI.getText());
                    newInversor.setNombre(TextoNombre.getText());
                    newInversor.setPiso(Integer.parseInt(TextoPiso.getText()));
                    newInversor.setPortal(Integer.parseInt(TextoPortal.getText()));
                    newInversor.setPuerta(TextoPuerta.getText());
                    newInversor.setTelefono(Integer.parseInt(TextoTelefono.getText()));
                    newInversor.getId_usuario().setId_usuario(TextoID.getText());

                    fa.modificarUsuario(newInversor.getId_usuario(), idAntiguo);
                    fa.modificarDatosInversor(newInversor);
                    


                    inversor = fa.consultarUnInversor(fa.consultarUnUsuario(TextoID.getText()));



                    fa.muestraExcepcion("Inversor modificado correctamente.");
                    etiquetaResultadoAccion.setVisible(false);
                }else{
                    fa.muestraExcepcion("Introduzca números válidos.");
                }

            } catch (NumberFormatException e) {
                etiquetaResultadoAccion.setText("Alguno de los campos teléfono, portal y piso tienen letras.");
                etiquetaResultadoAccion.setVisible(true);
            }
        } else {
            etiquetaResultadoAccion.setText("Completa todos los campos.");
            etiquetaResultadoAccion.setVisible(true);

        }

    }
}
